### ISSUE TITLE
Error from using regex::internal::Input in code 

### ISSUE THREAD

**Issue by dawkaka** [httpmock/httpmock#88]
**httpmock version**: 0.6
**rust version**:  rustc 1.73.0-nightly (39f42ad9e 2023-07-19)

**Current Behavior**:

![Screenshot from 2023-07-20 09-43-05](https://github.com/alexliesenfeld/httpmock/assets/49823605/bc15e1c6-c82c-4ca9-8de2-a5c57549dc6b)

**Work around**: Removing `use regex::internal::Input` from `src/server/mod.rs` file fixed the problem

**Comment by alexliesenfeld** [comment]
Thanks. It’s fixed in the newest version, v0.6.8
